[package]
name = "aoc2023"
version = "1.0.0"
authors = ["João Conde <joaodiasconde@gmail.com>"]
edition = "2021"
default-run = "aoc2023"

[profile.release]
opt-level = 3
debug = false
lto = true

[dependencies]
regex = "1.10.6"
