[package]
name = "aoc2020"
version = "1.0.0"
authors = ["João Conde <joaodiasconde@gmail.com>"]
edition = "2018"
default-run = "aoc2020"

[dependencies]
regex = "1.4"
itertools = "0.9"

[profile.release]
opt-level = 3
debug = false
lto = true
