name: AoC 2020 Workflow
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup install 1.50.0
      - run: rustup default 1.50.0
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt --all -- --check
        working-directory: 2020/
      - run: cargo clippy -- -D clippy::all
        working-directory: 2020/
      - run: cargo build --release
        working-directory: 2020/
