name: AoC 2021 Workflow
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 16.13.0
      - run: yarn install
        working-directory: 2021/
      - run: yarn run build
        working-directory: 2021/
      - run: yarn run pretty
        working-directory: 2021/
