name: AoC 2022 Workflow
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://raw.githubusercontent.com/scalameta/scalafmt/master/bin/install-scalafmt-native.sh | bash -s -- 3.6.1 $(pwd)/scalafmt
      - run: ls
      - run: ./scalafmt
      - run: ./scalafmt --version
      - run: ./scalafmt src/*.scala
