name: AoC 2022 Workflow
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
        working-directory: 2022/
