name: 2023
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup install 1.74.0
      - run: rustup default 1.74.0
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - run: cargo fmt --all -- --check
        working-directory: 2023/
      - run: cargo clippy -- -D clippy::all
        working-directory: 2023/
      - run: cargo build --release
        working-directory: 2023/
